// Data for /system-design (Vue Flow). Every node and edge mirrors docs/system-design/*.md and the code they cite.

export type DiagramSide = 'top' | 'right' | 'bottom' | 'left'

/** client = a browser, app = our Nuxt/Nitro code, store = where data lives, external = a third party */
export type DiagramNodeKind = 'client' | 'app' | 'store' | 'external'

export interface DiagramNode {
	id: string
	label: string
	/** Second line: the technology, file or table behind the box (kept in its real case). */
	detail?: string
	kind: DiagramNodeKind
	/** Described in the docs, not shipped yet. */
	planned?: boolean
	x: number
	y: number
}

export interface DiagramEdge {
	from: string
	to: string
	label?: string
	fromSide?: DiagramSide
	toSide?: DiagramSide
}

export interface SystemDesignDiagram {
	id: string
	title: string
	/** 2–4 sentences; also the text alternative of the canvas. */
	summary: string
	/** File name under docs/system-design/. */
	doc: string
	nodes: DiagramNode[]
	edges: DiagramEdge[]
}

export const systemDesignDiagrams: SystemDesignDiagram[] = [
	{
		id: 'architecture',
		title: 'high-level architecture',
		summary:
			'resell.sh is a modular monolith: one Nuxt app renders the pages and serves the API, so there is no separate backend. The browser reaches it through Railway’s edge, which terminates TLS and spreads requests over the app replicas. Each replica is stateless: data lives in PostgreSQL, shared cache and rate limits in Redis, photos and digital files in an S3 bucket. Stripe moves the money and calls back with signed webhooks; Resend delivers the emails.',
		doc: '03-architecture.md',
		nodes: [
			{
				id: 'browser',
				label: 'browser',
				detail: 'vue 3 + nuxt ui',
				kind: 'client',
				x: 0,
				y: 140,
			},
			{
				id: 'edge',
				label: 'railway edge',
				detail: 'tls, x-real-ip',
				kind: 'external',
				x: 240,
				y: 140,
			},
			{
				id: 'app',
				label: 'nuxt app replicas',
				detail: 'nitro on bun: ssr + /api',
				kind: 'app',
				x: 480,
				y: 140,
			},
			{ id: 'pg', label: 'postgresql', detail: 'drizzle orm', kind: 'store', x: 760, y: 0 },
			{
				id: 'redis',
				label: 'redis',
				detail: 'cache, limits, jobs',
				kind: 'store',
				x: 760,
				y: 140,
			},
			{ id: 's3', label: 's3 bucket', detail: 'nuxthub blob', kind: 'store', x: 760, y: 280 },
			{
				id: 'stripe',
				label: 'stripe',
				detail: 'checkout + connect',
				kind: 'external',
				x: 360,
				y: 340,
			},
			{
				id: 'resend',
				label: 'resend',
				detail: 'transactional email',
				kind: 'external',
				x: 600,
				y: 420,
			},
		],
		edges: [
			{ from: 'browser', to: 'edge', label: 'https' },
			{ from: 'edge', to: 'app', label: 'request' },
			{ from: 'app', to: 'pg', label: 'sql' },
			{ from: 'app', to: 'redis', label: 'cache + buckets' },
			{ from: 'app', to: 's3', label: 'photos, files' },
			{
				from: 'app',
				to: 'stripe',
				label: 'sessions, transfers',
				fromSide: 'bottom',
				toSide: 'right',
			},
			{
				from: 'stripe',
				to: 'app',
				label: 'signed webhooks',
				fromSide: 'top',
				toSide: 'left',
			},
			{ from: 'app', to: 'resend', label: 'emails', fromSide: 'bottom', toSide: 'top' },
		],
	},
	{
		id: 'request-lifecycle',
		title: 'request lifecycle on the server',
		summary:
			'Every API request passes the same gates in order. nuxt-security adds the headers and CSP nonce and enforces size and rate limits; the CSRF middleware refuses cookie-authenticated mutations from another origin. There is no auth middleware: each handler asks for what it needs (requireUser, requireShopOwner), then validates the body with the shared Zod schema before Drizzle touches the database. Errors leave as createError with safe messages, never stack traces.',
		doc: '03-architecture.md',
		nodes: [
			{
				id: 'browser',
				label: 'browser',
				detail: 'cookie or Bearer token',
				kind: 'client',
				x: 0,
				y: 0,
			},
			{
				id: 'security',
				label: 'nuxt-security',
				detail: 'headers, csp, rate limit',
				kind: 'app',
				x: 240,
				y: 0,
			},
			{
				id: 'csrf',
				label: 'csrf middleware',
				detail: 'server/middleware/csrf.ts',
				kind: 'app',
				x: 480,
				y: 0,
			},
			{
				id: 'handler',
				label: 'route handler',
				detail: 'server/api/**',
				kind: 'app',
				x: 720,
				y: 0,
			},
			{
				id: 'auth',
				label: 'auth helpers',
				detail: 'server/utils/auth.ts',
				kind: 'app',
				x: 720,
				y: 170,
			},
			{
				id: 'zod',
				label: 'zod validation',
				detail: 'shared/schemas/',
				kind: 'app',
				x: 480,
				y: 170,
			},
			{
				id: 'drizzle',
				label: 'drizzle orm',
				detail: 'server/db/',
				kind: 'app',
				x: 240,
				y: 170,
			},
			{
				id: 'db',
				label: 'database',
				detail: 'postgresql or sqlite',
				kind: 'store',
				x: 0,
				y: 170,
			},
		],
		edges: [
			{ from: 'browser', to: 'security', label: 'request' },
			{ from: 'security', to: 'csrf', label: 'allowed' },
			{ from: 'csrf', to: 'handler', label: 'same origin' },
			{ from: 'handler', to: 'auth', label: '1. who?', fromSide: 'bottom', toSide: 'top' },
			{ from: 'auth', to: 'zod', label: '2. user', fromSide: 'left', toSide: 'right' },
			{
				from: 'zod',
				to: 'drizzle',
				label: '3. typed body',
				fromSide: 'left',
				toSide: 'right',
			},
			{ from: 'drizzle', to: 'db', label: 'sql', fromSide: 'left', toSide: 'right' },
			{
				from: 'handler',
				to: 'browser',
				label: 'json or createError',
				fromSide: 'top',
				toSide: 'top',
			},
		],
	},
	{
		id: 'money-flow',
		title: 'money flow',
		summary:
			'The server re-prices the cart, writes the order, then sends the buyer to Stripe Checkout for one charge. Stripe’s signed webhook marks the order paid and each seller gets a Stripe transfer of their share minus the 10% fee. Refunds are full and per seller order: refund first, then pull the payout back with a transfer reversal. Every step appends a row to transaction_logs, and idempotency keys make Stripe retries harmless.',
		doc: '05-money-flow.md',
		nodes: [
			{ id: 'cart', label: 'cart', detail: 'cart_items', kind: 'client', x: 0, y: 0 },
			{
				id: 'checkout',
				label: 'checkout',
				detail: 'POST /api/checkout',
				kind: 'app',
				x: 240,
				y: 0,
			},
			{
				id: 'stripe',
				label: 'stripe checkout',
				detail: 'hosted payment page',
				kind: 'external',
				x: 480,
				y: 0,
			},
			{
				id: 'webhook',
				label: 'webhook',
				detail: 'POST /api/stripe/webhook',
				kind: 'app',
				x: 720,
				y: 0,
			},
			{
				id: 'fulfil',
				label: 'fulfil order',
				detail: 'fulfillCheckout()',
				kind: 'app',
				x: 720,
				y: 170,
			},
			{
				id: 'transfers',
				label: 'transfer per seller',
				detail: 'transferToSeller()',
				kind: 'external',
				x: 480,
				y: 170,
			},
			{
				id: 'refunds',
				label: 'refund + reversal',
				detail: 'refundSellerOrder()',
				kind: 'app',
				x: 240,
				y: 170,
			},
			{
				id: 'ledger',
				label: 'transaction_logs',
				detail: 'append-only ledger',
				kind: 'store',
				x: 360,
				y: 360,
			},
		],
		edges: [
			{ from: 'cart', to: 'checkout', label: 'addressId only' },
			{ from: 'checkout', to: 'stripe', label: 'session url' },
			{ from: 'stripe', to: 'webhook', label: 'session.completed' },
			{
				from: 'webhook',
				to: 'fulfil',
				label: 'verified event',
				fromSide: 'bottom',
				toSide: 'top',
			},
			{
				from: 'fulfil',
				to: 'transfers',
				label: 'subtotal − fee',
				fromSide: 'left',
				toSide: 'right',
			},
			{
				from: 'transfers',
				to: 'refunds',
				label: 'seller refunds',
				fromSide: 'left',
				toSide: 'right',
			},
			{
				from: 'checkout',
				to: 'ledger',
				label: 'checkout.created',
				fromSide: 'left',
				toSide: 'left',
			},
			{
				from: 'fulfil',
				to: 'ledger',
				label: 'payment.succeeded',
				fromSide: 'bottom',
				toSide: 'right',
			},
			{
				from: 'transfers',
				to: 'ledger',
				label: 'transfer.created',
				fromSide: 'bottom',
				toSide: 'top',
			},
			{
				from: 'refunds',
				to: 'ledger',
				label: 'refund.created',
				fromSide: 'bottom',
				toSide: 'left',
			},
		],
	},
	{
		id: 'data-model',
		title: 'data model',
		summary:
			'Twelve of the 19 tables carry the marketplace. One order is split into a seller order per shop, so each seller ships, refunds and gets paid on their own. Order items snapshot the title and price at purchase time, and digital items unlock download grants with a counter and an expiry. Money events hang off orders and seller orders in transaction_logs.',
		doc: '04-data-model.md',
		nodes: [
			{
				id: 'users',
				label: 'users',
				detail: 'role: user | admin',
				kind: 'store',
				x: 480,
				y: 0,
			},
			{
				id: 'cart_items',
				label: 'cart_items',
				detail: 'buyer’s cart',
				kind: 'store',
				x: 0,
				y: 160,
			},
			{
				id: 'shops',
				label: 'shops',
				detail: 'stripe_account_id',
				kind: 'store',
				x: 240,
				y: 160,
			},
			{
				id: 'orders',
				label: 'orders',
				detail: 'pending → paid',
				kind: 'store',
				x: 720,
				y: 160,
			},
			{
				id: 'product_types',
				label: 'product_types',
				detail: 'physical | digital',
				kind: 'store',
				x: 0,
				y: 320,
			},
			{
				id: 'products',
				label: 'products',
				detail: 'price_cents, stock',
				kind: 'store',
				x: 240,
				y: 320,
			},
			{
				id: 'seller_orders',
				label: 'seller_orders',
				detail: 'payout_cents',
				kind: 'store',
				x: 720,
				y: 320,
			},
			{
				id: 'transaction_logs',
				label: 'transaction_logs',
				detail: 'append-only',
				kind: 'store',
				x: 960,
				y: 240,
			},
			{
				id: 'product_images',
				label: 'product_images',
				detail: 'public photos',
				kind: 'store',
				x: 0,
				y: 480,
			},
			{
				id: 'product_files',
				label: 'product_files',
				detail: 'private files',
				kind: 'store',
				x: 240,
				y: 480,
			},
			{
				id: 'order_items',
				label: 'order_items',
				detail: 'price snapshot',
				kind: 'store',
				x: 720,
				y: 480,
			},
			{
				id: 'download_grants',
				label: 'download_grants',
				detail: 'max_downloads, expires_at',
				kind: 'store',
				x: 480,
				y: 620,
			},
		],
		edges: [
			{ from: 'users', to: 'cart_items', label: 'fills', fromSide: 'left', toSide: 'top' },
			{ from: 'users', to: 'shops', label: 'owns 0..1', fromSide: 'bottom', toSide: 'top' },
			{ from: 'users', to: 'orders', label: 'places', fromSide: 'right', toSide: 'top' },
			{ from: 'shops', to: 'products', label: 'sells', fromSide: 'bottom', toSide: 'top' },
			{
				from: 'product_types',
				to: 'products',
				label: 'classifies',
				fromSide: 'right',
				toSide: 'left',
			},
			{
				from: 'products',
				to: 'product_images',
				label: 'shows',
				fromSide: 'bottom',
				toSide: 'top',
			},
			{
				from: 'products',
				to: 'product_files',
				label: 'delivers',
				fromSide: 'bottom',
				toSide: 'top',
			},
			{
				from: 'orders',
				to: 'seller_orders',
				label: 'split into',
				fromSide: 'bottom',
				toSide: 'top',
			},
			{
				from: 'shops',
				to: 'seller_orders',
				label: 'receives',
				fromSide: 'right',
				toSide: 'left',
			},
			{
				from: 'seller_orders',
				to: 'order_items',
				label: 'contains',
				fromSide: 'bottom',
				toSide: 'top',
			},
			{
				from: 'order_items',
				to: 'download_grants',
				label: 'grants',
				fromSide: 'bottom',
				toSide: 'right',
			},
			{
				from: 'product_files',
				to: 'download_grants',
				label: 'unlocks',
				fromSide: 'bottom',
				toSide: 'left',
			},
			{
				from: 'orders',
				to: 'transaction_logs',
				label: 'money events',
				fromSide: 'right',
				toSide: 'top',
			},
			{
				from: 'seller_orders',
				to: 'transaction_logs',
				label: 'money events',
				fromSide: 'right',
				toSide: 'bottom',
			},
		],
	},
	{
		id: 'scaling',
		title: 'scaling out',
		summary:
			'More traffic means more copies of the app, not a bigger one. Railway’s edge (or Caddy, when self-hosting with docker compose) spreads requests round robin over N replicas and health-checks /api/health. No sticky sessions are needed because the session is a sealed cookie. Anything shared lives outside the process: Redis holds the 30-second stale-while-revalidate cache, the rate-limit buckets and the BullMQ mail queue; PostgreSQL and S3 hold the data and files.',
		doc: '09-scaling-and-load-balancing.md',
		nodes: [
			{
				id: 'internet',
				label: 'internet',
				detail: 'buyers, sellers, stripe',
				kind: 'client',
				x: 0,
				y: 160,
			},
			{
				id: 'lb',
				label: 'load balancer',
				detail: 'railway edge or caddy',
				kind: 'external',
				x: 240,
				y: 160,
			},
			{ id: 'app1', label: 'app replica 1', detail: 'stateless', kind: 'app', x: 500, y: 0 },
			{
				id: 'app2',
				label: 'app replica 2',
				detail: 'stateless',
				kind: 'app',
				x: 500,
				y: 160,
			},
			{
				id: 'appn',
				label: 'app replica n',
				detail: 'stateless',
				kind: 'app',
				x: 500,
				y: 320,
			},
			{
				id: 'redis',
				label: 'redis',
				detail: 'cache 30 s swr, rate limits, bullmq mail queue',
				kind: 'store',
				x: 780,
				y: 0,
			},
			{
				id: 'pg',
				label: 'postgresql',
				detail: 'orders, ledger',
				kind: 'store',
				x: 780,
				y: 160,
			},
			{
				id: 's3',
				label: 's3 bucket',
				detail: 'photos, digital files',
				kind: 'store',
				x: 780,
				y: 320,
			},
		],
		edges: [
			{ from: 'internet', to: 'lb', label: 'https' },
			{ from: 'lb', to: 'app1', label: 'round robin' },
			{ from: 'lb', to: 'app2' },
			{ from: 'lb', to: 'appn' },
			{ from: 'app1', to: 'redis', label: 'shared state' },
			{ from: 'app2', to: 'pg', label: 'sql' },
			{ from: 'appn', to: 's3', label: 'blobs' },
			{ from: 'app1', to: 'pg' },
			{ from: 'appn', to: 'pg' },
			{ from: 'app2', to: 'redis' },
			{ from: 'app2', to: 's3' },
		],
	},
	{
		id: 'observability',
		title: 'observability (phase 22)',
		summary:
			'Being built in phase 22, so the boxes are dashed. An OpenTelemetry SDK in a Nitro plugin traces HTTP requests, database queries and Stripe calls and ships them over OTLP to Tempo. Prometheus scrapes request, checkout and queue metrics; JSON logs carrying the trace id land in Loki. Grafana reads all three, so a slow checkout can be followed from the metric to its trace to its log lines.',
		doc: '10-observability.md',
		nodes: [
			{
				id: 'app',
				label: 'nuxt app replicas',
				detail: 'opentelemetry sdk',
				kind: 'app',
				planned: true,
				x: 0,
				y: 160,
			},
			{
				id: 'collector',
				label: 'otel collector',
				detail: 'receives otlp',
				kind: 'external',
				planned: true,
				x: 260,
				y: 0,
			},
			{
				id: 'tempo',
				label: 'tempo',
				detail: 'traces',
				kind: 'store',
				planned: true,
				x: 520,
				y: 0,
			},
			{
				id: 'prometheus',
				label: 'prometheus',
				detail: 'metrics',
				kind: 'store',
				planned: true,
				x: 520,
				y: 160,
			},
			{
				id: 'loki',
				label: 'loki',
				detail: 'logs',
				kind: 'store',
				planned: true,
				x: 520,
				y: 320,
			},
			{
				id: 'grafana',
				label: 'grafana',
				detail: 'dashboards + alerts',
				kind: 'client',
				planned: true,
				x: 800,
				y: 160,
			},
		],
		edges: [
			{ from: 'app', to: 'collector', label: 'traces (otlp)' },
			{ from: 'collector', to: 'tempo', label: 'spans' },
			{
				from: 'prometheus',
				to: 'app',
				label: 'scrapes metrics',
				fromSide: 'left',
				toSide: 'right',
			},
			{
				from: 'app',
				to: 'loki',
				label: 'json logs + trace id',
				fromSide: 'bottom',
				toSide: 'left',
			},
			{ from: 'tempo', to: 'grafana', label: 'traces' },
			{ from: 'prometheus', to: 'grafana', label: 'metrics' },
			{ from: 'loki', to: 'grafana', label: 'logs' },
		],
	},
]
